### PR TITLE
Some basic updates

### PR DESCRIPTION
**Pull request by rolies106**
- #4 adding some button at homepage for disaster reporting
- Add basic db configuration
- Remove pgsql packages

### CODE REVIEW

**Comment by iromli** [comment]
kayaknya conflict

**Comment by pakMann** [comment]
@iromli biar dulu, tunggu @fachriza PR dulu

**Comment by fachriza** [comment]
weis ..

**Comment by iromli** [comment]
error di oil console karena https://github.com/gudeg-united/mishAPP/blob/1db69e7df34d139836340820605f35a58393c653/fuel/app/config/config.php#L13-L16

**Comment by rolies106** [comment]
@iromli my bad, already solved, will be pushed right away

**Comment by rolies106** [comment]
@iromli fetch mang

**Comment by iromli** [comment]
udin, thanks

**Pull request merged**
